# Generated by Django 5.1 on 2024-09-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_rename_descripción_alumno_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
