# Generated by Django 5.1 on 2024-09-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_alumno_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='descripcion',
            field=models.IntegerField(),
        ),
    ]
