# Generated by Django 5.1 on 2024-11-17 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='evento.estado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='materia.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='profesor.profesor')),
                ('tipo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='evento.tipo')),
            ],
        ),
    ]
