# Generated by Django 5.1 on 2024-10-30 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.BooleanField()),
                ('cursada', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursada.cursada')),
            ],
        ),
    ]
