<<<<<<<< HEAD:Vamoyvemo/ifts/apps/inscripcion/migrations/0001_initial.py
# Generated by Django 5.1 on 2024-10-22 20:45
========
# Generated by Django 5.1 on 2024-10-30 01:28
>>>>>>>> origin/Dev_final:Vamoyvemo/ifts/apps/materia/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<<< HEAD:Vamoyvemo/ifts/apps/inscripcion/migrations/0001_initial.py
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.BooleanField()),
========
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=50)),
>>>>>>>> origin/Dev_final:Vamoyvemo/ifts/apps/materia/migrations/0001_initial.py
            ],
        ),
    ]
